version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
  - package-ecosystem: npm
    directories:
      - /
      - /token-issuer/typescript
      - /ohttp/typescript
      - /ohttp/cloudflare
      - /registry/cloudflare
      - /examples/collector
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
  - package-ecosystem: pip
    directories:
      - /token-issuer/python
      - /ohttp/python
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
